### ISSUE TITLE
[BUG] Pricing not showing well after publishing a dataset using nautilus

### ISSUE THREAD

**Issue by freevedo33** [deltaDAO/nautilus#144]
## Summary

**_Maybe not a bug._**
Hi everyone. 
When trying to publish a dataset with a specific price using nautilus, I noticed that the price showed later on the marketplace catalogue does not appear well. 
For example, when given 1 Ocean, in the catalogue the price will be 1.001 Ocean. When I use the editPrice function, it seems to work fine. 

Maybe it is an understanding problem my side.
## Current Behavior

  Price is 1.001 Ocean
## Expected Behavior

1 Ocean
## Steps to Reproduce

Here you can see my pricing config: 
```
export const PRICING_CONFIGS: PricingConfig = {

  [Network.PONTUSX]: {

    FREE: {

      type: 'free'

    },

    FIXED_OCEAN: {

      type: 'fixed',


      freCreationParams: {

        fixedRateAddress: '0xAD8E7d2aFf5F5ae7c2645a52110851914eE6664b',

        baseTokenAddress: '0x0995527d3473b3a98c471f1ed8787acd77fbf009',

        baseTokenDecimals: 18,

        datatokenDecimals: 18,

        fixedRate: '1',

        marketFee: '0',

        marketFeeCollector: '0x0000000000000000000000000000000000000000'

      }

    },

    FIXED_EUROE: {

      type: 'fixed',

      freCreationParams: {

        fixedRateAddress: '0xAD8E7d2aFf5F5ae7c2645a52110851914eE6664b',

        baseTokenAddress: '0xe974c4894996E012399dEDbda0bE7314a73BBff1',

        baseTokenDecimals: 6, // adapted for EUROe decimals

        datatokenDecimals: 18,

        fixedRate: '1',

        marketFee: '0',

        marketFeeCollector: '0x0000000000000000000000000000000000000000'

      }

    }

  },
```
Maybe I should change something in the configuration. 

## Environment

- OS: Windows 10 Entreprise
- Node: v18.20.2
- npm: 10.5.0

**Comment by kaimeinke** [comment]
Hi @freevedo33 , this is in fact not a bug and has nothing to do with your local configuration. You specified the price of the service provider correctly with 1.000, but the market fee of 0,1% is added with an amount of 0.001, which sums up to a total of 1.001.

<img width="1197" alt="image" src="https://github.com/deltaDAO/nautilus/assets/59994024/6271faca-7556-4e41-9b52-2f0c47e1ec20">

For every asset you will see a cost breakdown when hovering over the info icon.

<img width="331" alt="image" src="https://github.com/deltaDAO/nautilus/assets/59994024/0a7c7e53-9ba2-461e-9cba-de8f8113f0b3">

When observing the transaction itself, you will see that the fee is being substracted from the paid amount automatically which is part of the incentive system for the base services of the ecosystem to support sustainable operations for the ecosystem providers.

Example: https://explorer.pontus-x.eu/tx/0x02db1af6a043b4579868cc9e94f5d55a0ec677a31f3657392d293b61a15b8fe0

**Comment by freevedo33** [comment]
> Hi @freevedo33 , this is in fact not a bug and has nothing to do with your local configuration. You specified the price of the service provider correctly with 1.000, but the market fee of 0,1% is added with an amount of 0.001, which sums up to a total of 1.001.
> <img alt="image" width="1197" src="https://private-user-images.githubusercontent.com/59994024/333188285-6271faca-7556-4e41-9b52-2f0c47e1ec20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzQ3MTMsIm5iZiI6MTcxNjUzNDQxMywicGF0aCI6Ii81OTk5NDAyNC8zMzMxODgyODUtNjI3MWZhY2EtNzU1Ni00ZTQxLTliNTItMmYwYzQ3ZTFlYzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZWVlZTU0NWRmNjAwY2I4Y2ZhOGJjZjI1ZmUyYmVmZTI5Y2RjZTljZjZjMWZlYTIxZjBhOTJiYzY3NGIzNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7cuIfGPhSI8FCiM2waaV12W_8GIj7DllFBku42aFIBw">
> 
> For every asset you will see a cost breakdown when hovering over the info icon.
> <img alt="image" width="331" src="https://private-user-images.githubusercontent.com/59994024/333189327-0a7c7e53-9ba2-461e-9cba-de8f8113f0b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzQ3MTMsIm5iZiI6MTcxNjUzNDQxMywicGF0aCI6Ii81OTk5NDAyNC8zMzMxODkzMjctMGE3YzdlNTMtOWJhMi00NjFlLTljYmEtZGU4ZjgxMTNmMGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjN2I4NTJkZDgwOWQ4YTk4OGVlNDlmNzk4MTkyMjllMGRmZDVjMjE5ZTE1NTI5Yjk4MTc3NTE2YzBhZTc5YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rrTUcNkNJQZZ9ggEeT6xnpParoXr31FCbU4K43wBIfY">
> 
> When observing the transaction itself, you will see that the fee is being substracted from the paid amount automatically which is part of the incentive system for the base services of the ecosystem to support sustainable operations for the ecosystem providers.
> 
> Example: https://explorer.pontus-x.eu/tx/0x02db1af6a043b4579868cc9e94f5d55a0ec677a31f3657392d293b61a15b8fe0

Hi @kaimeinke,

Thank you for your answer. Now I understand it. 

Is there any community channels that I can use for questions about to nautilus ? like discord. Sometimes I don't have issues but only questions about the structure of nautilus.

Thanks.
