### ISSUE TITLE
[Enhancement] add missing DDO attributes

### ISSUE THREAD

**Issue by Abrom8** [deltaDAO/nautilus#31]
## Motivation / Problem
tags and copyrightHolder are missing in the assetBuilder

TODO: check for other missing attributes
TODO2: implement functions for all missing attributes

**Comment by rogargon** [comment]
Yes, we will need to set the tags. It would be helpful to do so through the AssetBuilder

**Comment by rogargon** [comment]
Others that seem missing are "license" and "links"

**Comment by rogargon** [comment]
For the moment got it working by doing:
```
const asset = assetBuilder.build();
asset.metadata.tags = ['tag1', 'tag2'];
asset.metadata.links = ['https://samples.org/file.csv'];
const result = await nautilus.publish(asset);
```
