### ISSUE TITLE
Error when using addTags(...)

### ISSUE THREAD

**Issue by rogargon** [deltaDAO/nautilus#43]
When using addTags, I'm getting the following error message:

TypeError: Cannot read properties of undefined (reading 'concat')

It seems related to the fact that when doing it for the first time, the array of tags used as the first parameter is undefined at:

https://github.com/deltaDAO/nautilus/blob/301b1b8cfb2e9dafb8da081074c12eb4f1e2891f/src/Nautilus/Asset/AssetBuilder.ts#L114

**Comment by moritzkirstein** [comment]
Thanks for opening the issue @rogargon 
There now is a fix available in the [v0.2.2](https://github.com/deltaDAO/nautilus/releases/tag/v0.2.2) version.
