### ISSUE TITLE
[BUG] Publishing dataset fails due to 'exceeds block gas limit' error

### ISSUE THREAD

**Issue by PixxelFD** [deltaDAO/nautilus#44]
## Summary
When trying to publish a dataset to the Gen-X network with the given configs a web3 error is thrown.

## Current Behavior
The publishing doesn't work and the error 'exceeds block gas limit' is thrown
  
## Expected Behavior
The dataset is published to the DLT and can be seen in the portal. 

### Network_Config:
    {
    network: 'genx',
    chainId: 100,
    metadataCacheUri: 'https://aquarius510.v4.delta-dao.com',
    nodeUri: 'https://rpc.genx.minimal-gaia-x.eu',
    providerUri: 'https://provider.v4.genx.delta-dao.com',
    subgraphUri: 'https://subgraph.v4.genx.minimal-gaia-x.eu',
    oceanTokenAddress: '0x0995527d3473b3a98c471f1ed8787acd77fbf009',
    oceanTokenDecimals: 18,
    oceanTokenSymbol: 'OCEAN',
    fixedRateExchangeAddress: '0xAD8E7d2aFf5F5ae7c2645a52110851914eE6664b',
    dispenserAddress: '0x94cb8FC8719Ed09bE3D9c696d2037EA95ef68d3e',
    nftFactoryAddress: '0x6cb85858183b82154921f68b434299ec4281da53',
    providerAddress: '0x68C24FA5b2319C81b34f248d1f928601D2E5246B',
    euroeAddress: '0xe974c4894996e012399dedbda0be7314a73bbff1',
    euroeDecimals: 6
    }

### Pricing_Config:
    type: 'fixed',
    freCreationParams: {
        fixedRateAddress: config.fixedRateExchangeAddress,
        baseTokenAddress: config.euroeAddress,
        baseTokenDecimals: config.euroeDecimals,
        datatokenDecimals: 18,
        fixedRate: '1',
        marketFee: '0',
        marketFeeCollector: '0x0000000000000000000000000000000000000000'
    }

### Error message:
\service-pub\node_modules\web3\node_modules\web3-core\lib\commonjs\web3_request_manager.js:258
                throw new web3_errors_1.InvalidResponseError(response, payload);
                      ^

InvalidResponseError: Returned error: exceeds block gas limit
    at Web3RequestManager._processJsonRpcResponse (\service-pub\node_modules\web3\node_modules\web3-core\lib\commonjs\web3_request_manager.js:258:23)
    at Web3RequestManager.<anonymous> (\service-pub\node_modules\web3\node_modules\web3-core\lib\commonjs\web3_request_manager.js:156:29)
    at Generator.next (<anonymous>)
    at fulfilled (\service-pub\node_modules\web3\node_modules\web3-core\lib\commonjs\web3_request_manager.js:21:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  innerError: { code: -32600, message: 'exceeds block gas limit' },
  code: 101,
  data: undefined,
  request: {
    jsonrpc: '2.0',
    id: '2a351139-c976-447a-8c48-c58e6a1711d0',
    method: 'eth_sendRawTransaction',
  }
}

## Environment
- OS: Windows 11
- Node: 18.15.0
- npm: 9.6.4

  
## Anything else
- It's not account dependent. I tried two different accounts for publishing and they both create this error.

**Comment by Abrom8** [comment]
Could you provide the `web3` and `nautilus` package versions you are currently using (specified in your `package.json`)?

**Comment by PixxelFD** [comment]
Even after reinstalling the packages and using the following versions, the error still occurs
``web3`` ^4.0.3
``nautilus`` ^0.2.2

**Comment by Abrom8** [comment]
Please try "1.9.0" for `web3`. We are experiencing issues with the other versions. Make sure to remove the remove the old installation. The easiest solution is to delete the `node_modules` folder and run `npm i` again.

**Comment by PixxelFD** [comment]
After experimenting a bit with the right web3 version and the tsconfig, the problem is resolved. Thank you.
